# Generated by Django 5.0.6 on 2026-05-01 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0003_add_share_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sheetimage',
            options={'ordering': ['page_number'], 'verbose_name': '曲谱图片', 'verbose_name_plural': '曲谱图片'},
        ),
        migrations.AlterField(
            model_name='sheetimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='sheetimage',
            name='image',
            field=models.ImageField(upload_to='sheets/%Y/%m/%d/', verbose_name='曲谱图片'),
        ),
        migrations.AlterField(
            model_name='sheetimage',
            name='page_number',
            field=models.PositiveIntegerField(default=0, verbose_name='页码'),
        ),
        migrations.AlterField(
            model_name='sheetimage',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sheets.guitarsheet', verbose_name='所属曲谱'),
        ),
    ]
