# Generated by Django 5.0.6 on 2026-05-02 06:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0004_fix_sheetimage_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_shared',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否共享'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='分类名称'),
        ),
        migrations.AlterField(
            model_name='guitarsheet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='guitarsheet',
            name='is_shared',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否共享'),
        ),
        migrations.AlterField(
            model_name='guitarsheet',
            name='title',
            field=models.CharField(db_index=True, max_length=200, verbose_name='曲谱名称'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_shared', 'share_token'], name='sheets_cate_is_shar_a9ced6_idx'),
        ),
        migrations.AddIndex(
            model_name='guitarsheet',
            index=models.Index(fields=['owner', 'category'], name='sheets_guit_owner_i_264e56_idx'),
        ),
        migrations.AddIndex(
            model_name='guitarsheet',
            index=models.Index(fields=['is_shared', 'share_token'], name='sheets_guit_is_shar_065e1a_idx'),
        ),
        migrations.AddIndex(
            model_name='guitarsheet',
            index=models.Index(fields=['title'], name='sheet_title_idx'),
        ),
        migrations.AddIndex(
            model_name='sheetimage',
            index=models.Index(fields=['sheet', 'page_number'], name='sheets_shee_sheet_i_52fa9c_idx'),
        ),
    ]
