# Generated by Django 5.0.6 on 2026-05-02 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0005_alter_category_is_shared_alter_category_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', '未开始'), ('practicing', '练习中'), ('mastered', '已掌握')], db_index=True, default='not_started', max_length=20, verbose_name='练习状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_progress', to='sheets.guitarsheet', verbose_name='曲谱')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_progress', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '练习进度',
                'verbose_name_plural': '练习进度',
                'indexes': [models.Index(fields=['user', 'status'], name='sheets_prac_user_id_0b2b8a_idx')],
                'unique_together': {('user', 'sheet')},
            },
        ),
    ]
