"""
Django settings for guitar_sheet_project project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


_BOOL_TRUTHY = frozenset({'1', 'true', 'yes', 'on'})
_BOOL_FALSY = frozenset({'0', 'false', 'no', 'off'})


def _env_bool(name: str, default: bool) -> bool:
    raw = os.environ.get(name)
    if raw is None:
        return default
    val = raw.strip().lower()
    if val in _BOOL_TRUTHY:
        return True
    if val in _BOOL_FALSY:
        return False
    raise ValueError(
        f'Environment variable {name}={raw!r} is not a valid boolean '
        f'(expected one of: {sorted(_BOOL_TRUTHY | _BOOL_FALSY)}).'
    )


def _allowed_hosts() -> list[str]:
    raw = os.environ.get('DJANGO_ALLOWED_HOSTS')
    if raw is None:
        return ['127.0.0.1', 'localhost']
    hosts = [h.strip() for h in raw.split(',') if h.strip()]
    return hosts if hosts else ['127.0.0.1', 'localhost']


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# 生产设置 DJANGO_DEBUG=0 或 false；未设置时默认为 True（本地开发）
DEBUG = _env_bool('DJANGO_DEBUG', True)

# DJANGO_SECRET_KEY：生产环境必须通过环境变量设置（勿提交到 Git）。
# 本地 DEBUG 模式未设置时自动生成临时密钥，方便开发启动。
_RAW_SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if _RAW_SECRET_KEY:
    SECRET_KEY = _RAW_SECRET_KEY
elif DEBUG:
    from django.core.management.utils import get_random_secret_key
    SECRET_KEY = get_random_secret_key()
else:
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured(
        'DJANGO_SECRET_KEY environment variable is required when DEBUG=False.'
    )

# 生产必须设置 DJANGO_ALLOWED_HOSTS=你的用户名.pythonanywhere.com（逗号分隔多个）
# 未设置环境变量时默认为本机，便于本地开发
ALLOWED_HOSTS = _allowed_hosts()

# HTTPS 站点（如 PythonAnywhere）在 DEBUG=False 时建议设置，例如：
# DJANGO_CSRF_TRUSTED_ORIGINS=https://你的用户名.pythonanywhere.com
_csrf_raw = os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS')
CSRF_TRUSTED_ORIGINS = (
    [o.strip() for o in _csrf_raw.split(',') if o.strip()]
    if _csrf_raw
    else []
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'sheets',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'guitar_sheet_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'guitar_sheet_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-guitar-sheets',
    }
}

# Security headers
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
